# Generated by Django 2.2 on 2021-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chulihou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jn', models.CharField(blank=True, db_column='JN', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('wy', models.IntegerField(blank=True, db_column='WY', null=True)),
                ('ar', models.IntegerField(blank=True, db_column='AR', null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('msr', models.CharField(blank=True, db_column='MSR', max_length=255, null=True)),
                ('jc', models.CharField(blank=True, db_column='JC', max_length=255, null=True)),
                ('wf', models.CharField(blank=True, db_column='WF', max_length=255, null=True)),
                ('cl', models.CharField(blank=True, db_column='CL', max_length=255, null=True)),
                ('cm', models.CharField(blank=True, db_column='CM', max_length=255, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=255, null=True)),
                ('jd', models.CharField(blank=True, db_column='JD', max_length=16383, null=True)),
                ('msl', models.FloatField(blank=True, db_column='MSL', null=True)),
                ('msh', models.FloatField(blank=True, db_column='MSH', null=True)),
                ('msm', models.FloatField(blank=True, db_column='MSM', null=True)),
            ],
            options={
                'db_table': 'chulihou',
                'managed': False,
            },
        ),
    ]
