# Generated by Django 2.2 on 2021-07-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bdrnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('bdrnk', models.FloatField(blank=True, db_column='BDrnk', null=True)),
            ],
            options={
                'db_table': 'bdrnk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('mds', models.FloatField(blank=True, db_column='MdS', null=True)),
                ('td', models.DecimalField(blank=True, db_column='TD', decimal_places=0, max_digits=32, null=True)),
                ('nd', models.DecimalField(blank=True, db_column='ND', decimal_places=0, max_digits=32, null=True)),
                ('bd', models.DecimalField(blank=True, db_column='BD', decimal_places=0, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'city_infos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityMds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('mds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city_mds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityRnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('msrnk', models.FloatField(blank=True, db_column='MSrnk', null=True)),
                ('tdrnk', models.FloatField(blank=True, db_column='TDrnk', null=True)),
                ('ndrnk', models.FloatField(blank=True, db_column='NDrnk', null=True)),
                ('bdrnk', models.FloatField(blank=True, db_column='BDrnk', null=True)),
            ],
            options={
                'db_table': 'city_rnk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fulltable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jn', models.CharField(blank=True, db_column='JN', max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('wy', models.IntegerField(blank=True, db_column='WY', null=True)),
                ('ar', models.IntegerField(blank=True, db_column='AR', null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('msr', models.CharField(blank=True, db_column='MSR', max_length=255, null=True)),
                ('jc', models.CharField(blank=True, db_column='JC', max_length=255, null=True)),
                ('wf', models.CharField(blank=True, db_column='WF', max_length=255, null=True)),
                ('cl', models.CharField(blank=True, db_column='CL', max_length=255, null=True)),
                ('cm', models.CharField(blank=True, db_column='CM', max_length=255, null=True)),
                ('contact', models.CharField(blank=True, db_column='Contact', max_length=255, null=True)),
                ('jd', models.CharField(blank=True, db_column='JD', max_length=16383, null=True)),
                ('msl', models.FloatField(blank=True, db_column='MSL', null=True)),
                ('msh', models.FloatField(blank=True, db_column='MSH', null=True)),
                ('msm', models.FloatField(blank=True, db_column='MSM', null=True)),
            ],
            options={
                'db_table': 'fulltable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Msrnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('msrnk', models.FloatField(blank=True, db_column='MSrnk', null=True)),
            ],
            options={
                'db_table': 'msrnk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ndrnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('ndrnk', models.FloatField(blank=True, db_column='NDrnk', null=True)),
            ],
            options={
                'db_table': 'ndrnk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tdrnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('tdrnk', models.FloatField(blank=True, db_column='TDrnk', null=True)),
            ],
            options={
                'db_table': 'tdrnk',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Chulihou',
        ),
    ]
